version: "3.7"
services:
  zookeeper:
    restart: always
    image: wurstmeister/zookeeper
  kafka:
    restart: always
    image: wurstmeister/kafka
    ports:
        - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: ${KAFKA_TOPIC}:1:1"
    depends_on:
        - zookeeper
  db:
    restart: always
    container_name: db
    image: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ${PG_SCHEMAPATH}:/docker-entrypoint-initdb.d
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
volumes:
  pgdata: