log:
  file:  ./aggregator.log
api:
  grpcport:  4445
db:
  dsn:  host=localhost port=5432 user=igor password=igor dbname=rotator sslmode=disable
  dialect: postgres
algo:
  name: bandit
queue:
  name: kafka
kafka:
  topic: topic_rotator
  minsize: 10
  maxsize: 100000
  consumergroup: consumer_group_1
  port: 9092