log:
  file:  ./aggregator.log
db:
  dsn:  host=localhost port=5432 user=igor password=igor dbname=rotator sslmode=disable
  dialect: postgres
algo:
  name: bandit
queue:
  name: kafka
kafka:
  topic: topic_rotator
  minsize: 10
  maxsize: 100000
  consumergroup: consumer_group_2
  addr: localhost:9092